CREATE TABLE IF NOT EXISTS payment_transaction (
    transaction_id VARCHAR(255) PRIMARY KEY,
    step INT,
    type VARCHAR(50),
    amount DOUBLE PRECISION,
    nameorig VARCHAR(255),
    namedest VARCHAR(255),
    isfraud INT,
    isflaggedfraud INT,
    timestamp BIGINT,
    transaction_datetime VARCHAR(255),
    customer_id VARCHAR(255) NOT NULL,
    source_system VARCHAR(50) NOT NULL,
    city VARCHAR(255),
    country VARCHAR(255),
    currency VARCHAR(10),
    channel VARCHAR(50),
    merchant VARCHAR(255),
    status VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS cash_in_transaction (
    transaction_id VARCHAR(255) PRIMARY KEY,
    step INT,
    type VARCHAR(50),
    amount DOUBLE PRECISION,
    nameorig VARCHAR(255),
    namedest VARCHAR(255),
    isfraud INT,
    isflaggedfraud INT,
    timestamp BIGINT,
    transaction_datetime VARCHAR(255),
    customer_id VARCHAR(255) NOT NULL,
    source_system VARCHAR(50) NOT NULL,
    city VARCHAR(255),
    country VARCHAR(255),
    currency VARCHAR(10),
    channel VARCHAR(50),
    merchant VARCHAR(255),
    status VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS cash_out_transaction (
    transaction_id VARCHAR(255) PRIMARY KEY,
    step INT,
    type VARCHAR(50),
    amount DOUBLE PRECISION,
    nameorig VARCHAR(255),
    namedest VARCHAR(255),
    isfraud INT,
    isflaggedfraud INT,
    timestamp BIGINT,
    transaction_datetime VARCHAR(255),
    customer_id VARCHAR(255) NOT NULL,
    source_system VARCHAR(50) NOT NULL,
    city VARCHAR(255),
    country VARCHAR(255),
    currency VARCHAR(10),
    channel VARCHAR(50),
    merchant VARCHAR(255),
    status VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS transfer_transaction (
    transaction_id VARCHAR(255) PRIMARY KEY,
    step INT,
    type VARCHAR(50),
    amount DOUBLE PRECISION,
    nameorig VARCHAR(255),
    namedest VARCHAR(255),
    isfraud INT,
    isflaggedfraud INT,
    timestamp BIGINT,
    transaction_datetime VARCHAR(255),
    customer_id VARCHAR(255) NOT NULL,
    source_system VARCHAR(50) NOT NULL,
    city VARCHAR(255),
    country VARCHAR(255),
    currency VARCHAR(10),
    channel VARCHAR(50),
    merchant VARCHAR(255),
    status VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS debit_transaction (
    transaction_id VARCHAR(255) PRIMARY KEY,
    step INT,
    type VARCHAR(50),
    amount DOUBLE PRECISION,
    nameorig VARCHAR(255),
    namedest VARCHAR(255),
    isfraud INT,
    isflaggedfraud INT,
    timestamp BIGINT,
    transaction_datetime VARCHAR(255),
    customer_id VARCHAR(255) NOT NULL,
    source_system VARCHAR(50) NOT NULL,
    city VARCHAR(255),
    country VARCHAR(255),
    currency VARCHAR(10),
    channel VARCHAR(50),
    merchant VARCHAR(255),
    status VARCHAR(50)
);
